services:
  postgres:
    image: postgres:latest
    container_name: ml_postgres
    restart: always
    ports:
      - "5434:5432" 
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: something
      POSTGRES_DB: main_database
    volumes:
      - ./data:/var/lib/postgresql/data 
      - ./dump:/db_dumps